// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKIQUBpfk_6eVbibN1MeEZEY0uommUvN4',
    appId: '1:52689183485:web:a46088b2355d35f3ed1494',
    messagingSenderId: '52689183485',
    projectId: 'myappl-382b0',
    authDomain: 'myappl-382b0.firebaseapp.com',
    storageBucket: 'myappl-382b0.appspot.com',
    measurementId: 'G-9FN2JEVTWQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVMZPw7XkSq8i8_Ck4p1aLLnXNH-KiDuc',
    appId: '1:52689183485:android:5b7119ba43925da0ed1494',
    messagingSenderId: '52689183485',
    projectId: 'myappl-382b0',
    storageBucket: 'myappl-382b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWzJLqo5huj75eDxXxJ9fmGhOQKUPifOI',
    appId: '1:52689183485:ios:3f942b89257f0879ed1494',
    messagingSenderId: '52689183485',
    projectId: 'myappl-382b0',
    storageBucket: 'myappl-382b0.appspot.com',
    iosClientId: '52689183485-g2v5gsn1gfrdu90d5ost548i5bueou9b.apps.googleusercontent.com',
    iosBundleId: 'com.enkasa.apple',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWzJLqo5huj75eDxXxJ9fmGhOQKUPifOI',
    appId: '1:52689183485:ios:3f942b89257f0879ed1494',
    messagingSenderId: '52689183485',
    projectId: 'myappl-382b0',
    storageBucket: 'myappl-382b0.appspot.com',
    iosClientId: '52689183485-g2v5gsn1gfrdu90d5ost548i5bueou9b.apps.googleusercontent.com',
    iosBundleId: 'com.enkasa.apple',
  );
}
